# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDevChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDevChallenge
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa'
  pod 'Cupcake'
  pod 'FontAwesome.swift'

  target 'SwiftDevChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftDevChallengeUITests' do
    # Pods for testing
  end

end
